---

- hosts: digitalocean

  vars:
    do_token: 97a1645209581608684221b6d3f6f5bb1293d3c5ccc0725d6aaf949db4b302ad
    droplets:
    - sb-docker

  tasks:

    - name: ensure ssh key exists
      user: >
          name={{ ansible_user_id }}
          generate_ssh_key=yes
          ssh_key_file=~/.ssh/id_rsa

    - name: ensure key exists at DigitalOcean
      digital_ocean: >
          state=present
          command=ssh
          name=sb_ssh_key
          ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
          api_token={{ do_token }}
      register: sb_ssh_key

    - name: ensure droplet one exists
      digital_ocean: >
         state=present
         command=droplet
         name={{ item }}
         size_id=2gb
         region_id=fra1
         virtio=yes
         unique_name=yes
         image_id=ubuntu-16-04-x64
         ssh_key_ids={{ sb_ssh_key.ssh_key.id }}
         api_token={{ do_token }}
      with_items: "{{ droplets }}"
      register: droplet_details

    - debug: msg="IP is {{ item.droplet.ip_address }}"
      with_items:
        - "{{ droplet_details.results }}"

    - local_action: lineinfile line="{{ item.droplet.ip_address }}" dest="newhost"
      with_items:
        - "{{ droplet_details.results }}"
